# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_new_product.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddNewProduct(object):
    def setupUi(self, AddNewProduct):
        AddNewProduct.setObjectName("AddNewProduct")
        AddNewProduct.resize(817, 350)
        self.label_2 = QtWidgets.QLabel(AddNewProduct)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 130, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(AddNewProduct)
        self.line.setGeometry(QtCore.QRect(0, 50, 811, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(AddNewProduct)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AddNewProduct)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AddNewProduct)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(AddNewProduct)
        self.label_6.setGeometry(QtCore.QRect(10, 220, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(AddNewProduct)
        self.label_7.setGeometry(QtCore.QRect(10, 270, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.product_code = QtWidgets.QLabel(AddNewProduct)
        self.product_code.setGeometry(QtCore.QRect(170, 70, 270, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_code.setFont(font)
        self.product_code.setText("")
        self.product_code.setObjectName("product_code")
        self.product_name = QtWidgets.QLineEdit(AddNewProduct)
        self.product_name.setGeometry(QtCore.QRect(170, 120, 611, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(18)
        self.product_name.setFont(font)
        self.product_name.setText("")
        self.product_name.setObjectName("product_name")
        self.product_price = QtWidgets.QLineEdit(AddNewProduct)
        self.product_price.setGeometry(QtCore.QRect(170, 170, 131, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_price.setFont(font)
        self.product_price.setText("")
        self.product_price.setAlignment(QtCore.Qt.AlignCenter)
        self.product_price.setObjectName("product_price")
        self.product_sale_price = QtWidgets.QLineEdit(AddNewProduct)
        self.product_sale_price.setEnabled(False)
        self.product_sale_price.setGeometry(QtCore.QRect(170, 270, 131, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_sale_price.setFont(font)
        self.product_sale_price.setText("")
        self.product_sale_price.setAlignment(QtCore.Qt.AlignCenter)
        self.product_sale_price.setObjectName("product_sale_price")
        self.product_is_sale = QtWidgets.QCheckBox(AddNewProduct)
        self.product_is_sale.setGeometry(QtCore.QRect(170, 220, 85, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_is_sale.setFont(font)
        self.product_is_sale.setObjectName("product_is_sale")
        self.btn_cancel = QtWidgets.QPushButton(AddNewProduct)
        self.btn_cancel.setGeometry(QtCore.QRect(410, 290, 150, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_add = QtWidgets.QPushButton(AddNewProduct)
        self.btn_add.setGeometry(QtCore.QRect(620, 290, 150, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.btn_add.setFont(font)
        self.btn_add.setDefault(True)
        self.btn_add.setObjectName("btn_add")

        self.retranslateUi(AddNewProduct)
        QtCore.QMetaObject.connectSlotsByName(AddNewProduct)

    def retranslateUi(self, AddNewProduct):
        _translate = QtCore.QCoreApplication.translate
        AddNewProduct.setWindowTitle(_translate("AddNewProduct", "Dialog"))
        self.label_2.setText(_translate("AddNewProduct", "新增商品"))
        self.label_3.setText(_translate("AddNewProduct", "商品條碼："))
        self.label_4.setText(_translate("AddNewProduct", "商品名稱："))
        self.label_5.setText(_translate("AddNewProduct", "商品價格："))
        self.label_6.setText(_translate("AddNewProduct", "是否特價："))
        self.label_7.setText(_translate("AddNewProduct", "特價價格："))
        self.product_is_sale.setText(_translate("AddNewProduct", "否"))
        self.btn_cancel.setText(_translate("AddNewProduct", "取消"))
        self.btn_add.setText(_translate("AddNewProduct", "新增"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddNewProduct = QtWidgets.QDialog()
    ui = Ui_AddNewProduct()
    ui.setupUi(AddNewProduct)
    AddNewProduct.show()
    sys.exit(app.exec_())
