# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_manager.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(810, 802)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 220, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 320, 165, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 370, 255, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.search_code = QtWidgets.QLineEdit(self.centralwidget)
        self.search_code.setGeometry(QtCore.QRect(200, 30, 270, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.search_code.setFont(font)
        self.search_code.setAlignment(QtCore.Qt.AlignCenter)
        self.search_code.setObjectName("search_code")
        self.product_code = QtWidgets.QLabel(self.centralwidget)
        self.product_code.setGeometry(QtCore.QRect(200, 120, 270, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_code.setFont(font)
        self.product_code.setObjectName("product_code")
        self.product_name = QtWidgets.QLabel(self.centralwidget)
        self.product_name.setGeometry(QtCore.QRect(200, 170, 601, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.product_name.setFont(font)
        self.product_name.setObjectName("product_name")
        self.product_price = QtWidgets.QLabel(self.centralwidget)
        self.product_price.setGeometry(QtCore.QRect(200, 220, 150, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_price.setFont(font)
        self.product_price.setObjectName("product_price")
        self.product_sale_price = QtWidgets.QLabel(self.centralwidget)
        self.product_sale_price.setGeometry(QtCore.QRect(200, 320, 150, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_sale_price.setFont(font)
        self.product_sale_price.setObjectName("product_sale_price")
        self.search_btn = QtWidgets.QPushButton(self.centralwidget)
        self.search_btn.setGeometry(QtCore.QRect(480, 30, 100, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.search_btn.setFont(font)
        self.search_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search_btn.setObjectName("search_btn")
        self.btn_remove_list = QtWidgets.QPushButton(self.centralwidget)
        self.btn_remove_list.setGeometry(QtCore.QRect(405, 280, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.btn_remove_list.setFont(font)
        self.btn_remove_list.setObjectName("btn_remove_list")
        self.btn_add_list = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_list.setGeometry(QtCore.QRect(580, 280, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.btn_add_list.setFont(font)
        self.btn_add_list.setObjectName("btn_add_list")
        self.btn_clean = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clean.setGeometry(QtCore.QRect(405, 360, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.btn_clean.setFont(font)
        self.btn_clean.setObjectName("btn_clean")
        self.btn_edit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(580, 360, 150, 50))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 90, 811, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 420, 811, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.message = QtWidgets.QTextBrowser(self.centralwidget)
        self.message.setGeometry(QtCore.QRect(0, 430, 811, 321))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(20)
        self.message.setFont(font)
        self.message.setObjectName("message")
        self.product_is_sale = QtWidgets.QLabel(self.centralwidget)
        self.product_is_sale.setGeometry(QtCore.QRect(200, 270, 85, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_is_sale.setFont(font)
        self.product_is_sale.setObjectName("product_is_sale")
        self.product_in_list = QtWidgets.QLabel(self.centralwidget)
        self.product_in_list.setGeometry(QtCore.QRect(290, 370, 85, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體 Light")
        font.setPointSize(20)
        self.product_in_list.setFont(font)
        self.product_in_list.setObjectName("product_in_list")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 810, 31))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu_manager = QtWidgets.QMenu(self.menubar)
        self.menu_manager.setObjectName("menu_manager")
        self.menu_card = QtWidgets.QMenu(self.menubar)
        self.menu_card.setObjectName("menu_card")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.product_manager = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.product_manager.setFont(font)
        self.product_manager.setObjectName("product_manager")
        self.product_all_card = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.product_all_card.setFont(font)
        self.product_all_card.setObjectName("product_all_card")
        self.actiontest = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.actiontest.setFont(font)
        self.actiontest.setObjectName("actiontest")
        self.product_card = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.product_card.setFont(font)
        self.product_card.setObjectName("product_card")
        self.product_card_in_list = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.product_card_in_list.setFont(font)
        self.product_card_in_list.setObjectName("product_card_in_list")
        self.menu_manager.addAction(self.product_manager)
        self.menu_card.addAction(self.product_card)
        self.menu_card.addAction(self.product_card_in_list)
        self.menu_card.addAction(self.product_all_card)
        self.menubar.addAction(self.menu_manager.menuAction())
        self.menubar.addAction(self.menu_card.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "商品條碼："))
        self.label_2.setText(_translate("MainWindow", "商品條碼："))
        self.label_3.setText(_translate("MainWindow", "商品名稱："))
        self.label_4.setText(_translate("MainWindow", "商品價格："))
        self.label_5.setText(_translate("MainWindow", "是否特價："))
        self.label_6.setText(_translate("MainWindow", "特價價格："))
        self.label_7.setText(_translate("MainWindow", "是否在列印清單："))
        self.search_code.setText(_translate("MainWindow", "1234567890123"))
        self.product_code.setText(_translate("MainWindow", "1234567890123"))
        self.product_name.setText(_translate("MainWindow", "一二三四五六七八九十一二三四五六七八九十"))
        self.product_price.setText(_translate("MainWindow", "9999元"))
        self.product_sale_price.setText(_translate("MainWindow", "9999元"))
        self.search_btn.setText(_translate("MainWindow", "查詢"))
        self.btn_remove_list.setText(_translate("MainWindow", "移除清單"))
        self.btn_add_list.setText(_translate("MainWindow", "加入清單"))
        self.btn_clean.setText(_translate("MainWindow", "清空"))
        self.btn_edit.setText(_translate("MainWindow", "編輯"))
        self.message.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微軟正黑體\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.product_is_sale.setText(_translate("MainWindow", "是"))
        self.product_in_list.setText(_translate("MainWindow", "是"))
        self.menu_manager.setTitle(_translate("MainWindow", "商品管理"))
        self.menu_card.setTitle(_translate("MainWindow", "價格牌管理"))
        self.product_manager.setText(_translate("MainWindow", "商品管理"))
        self.product_all_card.setText(_translate("MainWindow", "3 列印所有價格牌"))
        self.actiontest.setText(_translate("MainWindow", "test"))
        self.product_card.setText(_translate("MainWindow", "1 列印指定價格牌"))
        self.product_card_in_list.setText(_translate("MainWindow", "2 從清單中選取商品"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
